### ISSUE TITLE
Clicking on the Terracoin logo for the various language websites gives an error.

### ISSUE THREAD

**Issue by Arthur-salv** [terracoin/terracoinwebsite#18]
So when you click on the Terracoin logo in the top right corner you get an error.

Suomi:
https://terracoin.io/indeksi.html

Français:
https://terracoin.io/accueil.html

Nederlands:
https://terracoin.io/startpagina.html

Português:
https://terracoin.io/inicio.html

All errors.

**Comment by TheSin-** [comment]
you are correct it was a fix in _config.yml that was required and the fix was added it should make it live in the next few hours.
