### ISSUE TITLE
Linking to webpages other than English.

### ISSUE THREAD

**Issue by Arthur-salv** [terracoin/terracoinwebsite#19]
When I link to a Dutch TRC webpage, or any TRC webpage but the English ones, terracoin.io will automatically load the English main page. 

for example:
https://terracoin.io/team/ takes you to the Terracoin team page.
https://terracoin.io/team-nl/ takes you to terracoin.io

This is true for all languages. Whatever page you visit, when you copy & paste it in your browser it will simply take you to terracoin.io

**Comment by TheSin-** [comment]
yup this is true, the homepage was an after thought / bonus, I assume ppl will link to things in their own lang.  But I'll see if I can figure it out but VERY low priority.
